/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

const TermsOfServiceLazyRouteImport = createFileRoute("/terms-of-service")();
const PrivacyPolicyLazyRouteImport = createFileRoute("/privacy-policy")();

const TermsOfServiceLazyRoute = TermsOfServiceLazyRouteImport.update({
  id: "/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => rootRouteImport,
}).lazy(() => import("./routes/terms-of-service.lazy").then((d) => d.Route));
const PrivacyPolicyLazyRoute = PrivacyPolicyLazyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRouteImport,
}).lazy(() => import("./routes/privacy-policy.lazy").then((d) => d.Route));
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  TermsOfServiceLazyRoute: TermsOfServiceLazyRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
