/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const TermsOfServiceLazyImport = createFileRoute("/terms-of-service")();
const PrivacyPolicyLazyImport = createFileRoute("/privacy-policy")();

// Create/Update Routes

const TermsOfServiceLazyRoute = TermsOfServiceLazyImport.update({
  id: "/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => rootRoute,
}).lazy(() => import("./routes/terms-of-service.lazy").then((d) => d.Route));

const PrivacyPolicyLazyRoute = PrivacyPolicyLazyImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRoute,
}).lazy(() => import("./routes/privacy-policy.lazy").then((d) => d.Route));

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
});

// Create and export the route tree

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  TermsOfServiceLazyRoute: TermsOfServiceLazyRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren);

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/privacy-policy",
        "/terms-of-service"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.lazy.jsx"
    },
    "/terms-of-service": {
      "filePath": "terms-of-service.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
